//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecte_Chrysallis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistir
    {
        public int idSocio { get; set; }
        public short idEvento { get; set; }
        public Nullable<byte> valoracion { get; set; }
        public short numAsistentes { get; set; }
    
        public virtual Socios Socios { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
