//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecte_Chrysallis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int id { get; set; }
        public System.DateTime fechaHora { get; set; }
        public Nullable<short> idEvento { get; set; }
    
        public virtual Eventos Eventos { get; set; }
    }
}
